server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
    kubernetes:
      config:
        enabled: true
        name: config-map
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8085}
 
# Okta configurations for API Gateway
okta:
  oauth2:
    issuer: https://integrator-9230174.okta.com/oauth2/default
    audience: api://default
    client-id: 0oavmlvp1jG6VBHKu697
    client-secret: 5CYWiNQQAui4QiuF7AN-_BWDG0DDSWwhUAteQkb9onWFxB1BCUpcJj50ItH6NnVu
    scopes: openid, profile, email, offline_access # offline_access: This keeps the user signed in to the app, even when you are not using it
    
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}