apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-gateway
  namespace: default
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app:  api-gateway
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  api-gateway
        image:  manashbarman007/api-gateway:latest
        env:
        - name: EUREKA_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: EUREKA_SERVER_URL
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: CONFIG_SERVER_URL
        ports:
        - containerPort:  8084
          name:  api-gateway

          
---


apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
  - name: api-gateway-service
    protocol: TCP
    port: 8084
    targetPort: 8084
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-nodeport
  namespace: default
spec:
  selector:
    app: api-gateway
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: api-gateway-service-nodeport
    protocol: TCP
    port: 80
    targetPort: 8084
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30084