server:
  port: 8082
# MongoDB configuration
spring:
  application:
    name: HOTEL-SERVICE
  data:
    mongodb:
      database: hotel_microservicesDB
      uri: ${MONGO_DB_URI:mongodb://localhost:27017}


#  config:
#    import: optional:configserver:http://localhost:8085
  cloud:
    config:
      enabled: false
    kubernetes:
      config:
        enabled: true
        name: config-map
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-9230174.okta.com/oauth2/default
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true #true by default
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true #true by default

# Okta configurations for Hotel Service
okta:
  oauth2:
    audience: api://default
    issuer: https://integrator-9230174.okta.com/oauth2/default	